version: "3.8"

services:
  free5gc-upf-new:
    container_name: upf-new
    image: free5gc/upf:v4.2.1
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg-new.yaml"
    volumes:
      - ./config/upfcfg-new.yaml:/free5gc/config/upfcfg-new.yaml
      - ./config/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    privileged: true
